services:
  _defaults:
    autowire:       true
    autoconfigure:  true
    public:         true

##### Filter Mapper
  Austral\FilterBundle\Mapper\FilterMapper: "@austral.filter.mapper"
  austral.filter.mapper:
    class:          Austral\FilterBundle\Mapper\FilterMapper
    arguments:      [ "@request_stack", '@event_dispatcher', "@austral.filter.form.type", "@form.factory"]


##### Event Subscriber
  Austral\FilterBundle\EventSubscriber\FilterSubscriber:  "@austral.filter.event_subscriber"
  austral.filter.event_subscriber:
    class:          Austral\FilterBundle\EventSubscriber\FilterSubscriber
    arguments:      [ "@event_dispatcher" ]
    tags:
      - { name: kernel.event_subscriber }

##### Form Type
  Austral\FilterBundle\Form\Type\FilterFormType:  "@austral.filter.form.type"
  austral.filter.form.type:
    class:          Austral\FilterBundle\Form\Type\FilterFormType
    arguments:      [ "@security.authorization_checker" ]
    tags:
      - { name: form.type , alias: austral_filter_form_type }